name: Core Deployment

on:
  push:
    branches:
      - master
    paths:
      - 'core/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        working-directory: ./core
        run: yarn install
      - name: Run production build
        working-directory: ./core
        run: yarn run build
      - name: Push to NPM
        working-directory: ./core
        run: |
          npm version "v1.0.${GITHUB_RUN_NUMBER}"
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Ping Discord on failure
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{ secrets.WEBHOOK_URL_MERGE_FAILURE }}
          details: 'express-react-pdf merge workflow failed!'
