name: Core Checks

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Uses Node.js 14.17
        uses: actions/setup-node@v2
        with:
          node-version: 14.17
      - name: Enter core
        run: cd core
      - name: Install dependencies
        run: yarn install
      - name: Run prettier
        run: yarn prettier:check
      - name: Linter
        run: yarn lint
      - name: Spell check
        run: npx cspell "**/*.{md,js,ts,tsx}"
      - name: Run unit tests
        run: yarn test:unit
      - name: Run production build
        run: yarn build
